### ISSUE TITLE
[Feature request] The main icon for macOS needs some love

### ISSUE THREAD

**Issue by uctcs** [oleg68/GrandOrgue#20]
The large program icon looks very blurry on macOS (see attached screenshot). I do not know whether there is a version with a higher resolution available. If not I could try to improve the icon if desired.

![Screenshot](https://user-images.githubusercontent.com/82236523/116231298-f7209380-a758-11eb-84be-4abf7e903d40.jpg)

**Comment by oleg68** [comment]
I have only 32x32 pixel icon https://github.com/oleg68/GrandOrgue/blob/master/resources/GrandOrgue.icns. If you make a large image, how will it work with low screen resolutions?

**Comment by uctcs** [comment]
I have no idea. Looking into the Apple Human Interface Guidelines reveals that icons can be up to 1024x1024 px large.

[Apple Human Interface Guidelines -- App Icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

The current icon is really very tiny. I was not able to scale it meaningfully. We may consider creating a new high-resolution application icon.

**Comment by oleg68** [comment]
>  I could try to improve the icon if desired.

If you do it, I will replace GrandOrgue.icns with the new one.

**Comment by uctcs** [comment]
I am not a designer, but I tried my very best to create a modern-looking macOS icon, which follows the macOS Big Sur Apple Human Interface Guidelines.

I would appreciate any comments or recommendations on what to improve.

[macOS Icons GrandOrgue.zip](https://github.com/oleg68/GrandOrgue/files/6396980/macOS.Icons.GrandOrgue.zip)

![Screenshot](https://user-images.githubusercontent.com/82236523/116516883-771c3a00-a8ce-11eb-9b85-ea5b8fe89af8.jpg)

**Comment by oleg68** [comment]
Have you made it from svg? If so could you upload the source svg?

**Comment by uctcs** [comment]
I created the icon with Affinity Designer. The archive contains the original Affinity Designer file and an svg export.

[GrandOrgueIcon.zip](https://github.com/oleg68/GrandOrgue/files/6402532/GrandOrgueIcon.zip)

**Comment by oleg68** [comment]
Thank you for your work.

The icon must be the same in all GO builds: osx, linux and windows, but different OS require different icon file formats. So my idea is to put a svg file to the GrandOrgue source tree and to make OS-specific icon formats during the build process.

I'm going to choose GrandOrgue2.svg as a source file. Do you agree?

**Comment by uctcs** [comment]
That's fine!

**Comment by oleg68** [comment]
https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-6.os
