### ISSUE TITLE
[Bug report] macOS 11.3: panels do not open

### ISSUE THREAD

**Issue by ghost** [oleg68/GrandOrgue#21]
On some installations of macOS 11.3 the additional panels do not open or open somehow hidden in the background, as there is a checkmark in front of the menu entry. It is impossible to untick the invisible panels.

**Comment by uctcs** [comment]
I just found a workaround to correct this behavior. To write this post I had hidden GO. After unhiding it, it works correctly. This behavior is reproducible: hiding -- unhiding solves the issue.

BTW: This also solves the "black fullscreen" issue.

**Comment by oleg68** [comment]
The wrong behaviour of pannels is triggered by the entry in the info.plist file

```
	<key>CFBundleIdentifier</key>
	<string>com.our-organ.GrandOrgue</string>
```

I will make more research why this key prevents the pannels from opening.

**Comment by oleg68** [comment]
If I change `com.our-organ.GrandOrgue` to some another string, the pannels start opening too.

**Comment by uctcs** [comment]
I can confirm that this solves this issue. I changed `com.our-organ.GrandOrgue` to. `GrandOrgue` and it works.

But this creates another problem. I get now the error message:

Error: Failed to read directory '/Users/ ... /Organ packages'. Changing this key back to the standard value reintroduces the 'open panel' error, but removes the 'failed to read' error.

In addition, I am not able anymore to run GrandOrgue in light mode, when the OS is in dark mode. The GO dark mode colors do not work, e.g. it has white text on bright gray background. In addition, it is not possible anymore, to change the language of the program with 'System preferences > Language & regions > Apps'. I will add a separate bug report.

**Comment by oleg68** [comment]
@uctcs  The root cause of opening pannels problem is wrong user-wide setting for the application 'com.our-organ.GrandOrgue'.  `CFBundleIdentifier` sets which application to search setting for, so changing to some another value forces GrandOrgue to make new setting from scratch.

The workaround of this is
1. detach GrandOrgue*.dmg
2. Delete the subdirectory ``Library/Saved Application State/com.our-organ.GrandOrgue.savedState`` of the user home directory
3. Open GrandOrgue*.dmg again

Please check if this workaround works?

**Comment by oleg68** [comment]
> Error: Failed to read directory '/Users/ ... /Organ packages'. 

Usually this error appear when one running GrandOrgue outside the application bundle. Pleas run GrandOrgue from the dmg bundle.

**Comment by uctcs** [comment]
The previous recommendation (deleting `com.our-organ.GrandOrgue.savedState`) solved all issues:

- Panels do not open error
- GO can be started in bright mode on dark mode systems
- 'Failed to read directory ...' error

Was the file `com.our-organ.GrandOrgue.savedState` leftover from a pre-v0.3.1-2338 installation?

**Comment by oleg68** [comment]
> Was the file com.our-organ.GrandOrgue.savedState leftover from a pre-v0.3.1-2338 installation?

May be. This is a place where all windows positions and sizes are stored. Maybe https://github.com/oleg68/GrandOrgue/commit/55851f0cc1527466855d25316d3164a7a1734378 is not comparible with the old settings

**Comment by uctcs** [comment]
GrandOrgue works only correctly if the file `com.our-organ.GrandOrgue.savedState` is not present. Interestingly this file is not created when I run GO for the first time. I have to start GO 3 or 4 times before it appears. But as soon as it present, the issues are back again.

**Comment by oleg68** [comment]
This folder is created when you are doing `File`->`Save`. You can open several pannels, place and scale them and save their positions by 'Save' from the menu. `com.our-organ.GrandOrgue.savedState` should persist. Next time you start GrandOrgue it restores the saved parameters from there.

Seems sometimes when it appears it contains incorrect settings.

**Comment by uctcs** [comment]
The file also appears also without `File->Save`.

**Comment by oleg68** [comment]
Looking the sourcecode, GO stores positioning information in it's own config file rather `com.our-organ.GrandOrgue.savedState`. But OSx saves it there.

**Comment by oleg68** [comment]
Could you archive and attach your `com.our-organ.GrandOrgue.savedState` when the problem raises again?

**Comment by uctcs** [comment]
Hope that helps.

[com.our-organ.GrandOrgue.savedState.zip](https://github.com/oleg68/GrandOrgue/files/6412027/com.our-organ.GrandOrgue.savedState.zip)

**Comment by oleg68** [comment]
Since GrandOrgue started to build with wxWidgets 3.1, the issue is no more reproducible.

Seems it was a wxWidgets 3.0 issue.

Please reopen the issue if the problem appears again with the recent release of GrandOrgue
