### ISSUE TITLE
[Bug report] macOS 11.3 dark mode: some text is white on bright gray background

### ISSUE THREAD

**Issue by uctcs** [oleg68/GrandOrgue#24]
Some text  in dark mode is hard to read: white text on bright gray background. I attach a screenshot.

![Screenshot](https://user-images.githubusercontent.com/82236523/116818526-1dd13680-ab6c-11eb-80e5-84b11ec84c33.jpg)

**Comment by oleg68** [comment]
@uctcs I'm not familiar with OSx. How can I switch os to the dark mode?

**Comment by uctcs** [comment]
[System preferences > General > Appearence = dark](https://nektony.com/how-to/enable-dark-mode-macos)

**Comment by mattrixed** [comment]
Also have the issue on Catalina and Mojave - i've just had to switch back to light mode or once setup and don't need to alter anything put back to dark mode!

**Comment by oleg68** [comment]
Seems it will be resolved automatically with wxWidgets 3.1

**Comment by oleg68** [comment]
Fixed in https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-6.os
