### ISSUE TITLE
20 [Bug report] macOS 11.3: opening the About window makes the program unresponsive

### ISSUE THREAD

**Issue by uctcs** [oleg68/GrandOrgue#25]
After opening the About window the program becomes unresponsive. Clicking on the About window makes the window disappear. But all menu entries are now gray and cannot be selected anymore.

**Comment by mattrixed** [comment]
A fairly common issue across most platforms from memory in the past.  Especially mac. - i've learnt to not open about!!  Opening it on 2341 on windows seems to work no problem.

**Comment by oleg68** [comment]
Fixed in https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-8.os
