### ISSUE TITLE
GO releases on GIThub

### ISSUE THREAD

**Issue by Bumblebee001** [oleg68/GrandOrgue#32]
When I download the zipped file for windows and unzipped, the exe file ran the program straight away when clicked. It did not go through the process to install as we are accustomed to. I thought this was odd!

After I placed the unzipped folder in the place where I have a previous installation, correcting the names to include version number, an error keeps popping up in the log that the demo is not found. Yes I did alter the path, as it were, by changing the name, but why can't I correct it within GO? 🙁

**Comment by oleg68** [comment]
@Bumblebee001 Could you provide me more information?
1. What version of Windows are you using? 64bit or 32bit?
2. What version of Grandorgue zip did you take?
3. Is there another version of GrandOrgue installed on you system? What version is it?

>  the exe file ran the program straight away when clicked

4. Had any windows appeared before you clicked? What windows were?
5. Where did you click?
6. Could you repeat your stpes wit running the exe from the command prompt window. What is written in this window when GO goes away? Please copy and attach the text,

> an error keeps popping up in the log that the demo is not found

If you had a previous installation of GrandOrgue then you probably have an old config file ``Your user directory\Application Data\GrandOrgueConfig``. This file contains various pathes, including the path to the demo. If you change the path, you have two options
* Delete the old config and allow to srart GrandOrgue from scratch
* Run GrandOrgue, go to Audio/Midi -> Defaults and Initial Settings and put the correct path

>  but why can't I correct it within GO?

If you a talking about the path to the demo organ, then you can see them with Audio&MIdi -> Organ Packages. If are not correct, then you can delete them and install the demo organ with File -> Install Organ Package an to specify the correct path of demo organ

**Comment by Bumblebee001** [comment]
Ok... I discovered that there were two entries under "Organ packages" 
with old paths (referring to the 2 installations of GO I now have) and 2 
newer entries with the correct paths (as I have altered them to 
distinguish between them). I removed the older and kept the newer. No 
error messages coming up now.

So this part of the issue is solved.

What remains is the absence of the need to install GO. The downloaded 
zipped file, once unzipped, runs from the exe file in the bin folder.

Mark

**Comment by Bumblebee001** [comment]
There are 2 other issues I note with the DEMO organ:
(1) The samples used need editing. There is at least one note that 
produced a random loud audible click. I have not tested the whole set.
(2) When I close the demo organ, any notes still active remains sounding 
until I exit GO altogether.

Mark

**Comment by oleg68** [comment]
Thank for your answer.

Talking about the first part (necessariry of install) then you still haven't answer my questions 1 -  6  in my first comment.

Zip file is intended and tested for running on a pure system without previously insalled another version of GO.  So I need the information for reproducing and fixing it.

**Comment by oleg68** [comment]
> (1) The samples used need editing. There is at least one note that
produced a random loud audible click. I have not tested the whole set.

Please tell what note exactly.

> (2) When I close the demo organ, any notes still active remains sounding
until I exit GO altogether.

What are the steps to reprodoce? Is it:
1. Press some node on the midi keyboard without realeasing it
2. Close the organ

Or some notes remain sounding even after releasing the midi keys?

What audio device is selected In Audio/Midi -> Audio Output? Does it have `PA` prefix?

**Comment by oleg68** [comment]
@Bumblebee001 where can I download GO: v2330 for reproducing?

**Comment by Bumblebee001** [comment]
Oleg,

I think we are making this a bigger issue than it appears to be. I had downloaded v2330 from sourceforge as we all used to do, I assume. The file was an install file that allowed selection of a directory and renaming, or, default installation. I'm sure you yourself have done this in the past. The latest release, from GIThub, was a zipped file that unzips as a folder containing the GO subfolder and files with an executable GrandOrgue.exe that runs GO straight away. If anything, it is this zipped file that ought to be checked not v2330. 

Furthermore, I often installed multiple versions of GO in the past, up to 3 or 4 versions, in case I had issues with newer versions, I always had one or more previous reliable / stable installations to fall back on. I produce sample-sets for GO and having previous versions often helped to develop sets to accommodate those that did not upgrade their software so readily.

With regards to cmd prompt.... I did what you recommend but I got was a message that this was not an executable command!!!

Mark

**Comment by oleg68** [comment]
@Bumblebee001 

I tried to reproduce your actions. 

I installed v. 2334 (the only old version available for download from SourceForge) But every time when I unpack 2338-6 zip to some folder and double click on GrandOrgue.exe, the GrandOrgue pannels appears normally. 

When I extract only exe files from the zip without other folders, and double click GrandOrgue.exe, I receive an error message that dlls are missing

So I cann't reproduce the conditions when it cann't start without any error message.

Could you reproduce this again with unzipped files without installation? Or the problem went out?

> With regards to cmd prompt.... I did what you recommend but I got was a message that this was not an executable command!!!

Please mark (by clicking the mouse and keeping it pressed), copy the text you typed and the error message and paste it here.

Could you select the command

**Comment by Bumblebee001** [comment]
Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. All rights reserved.

C:\Users\mark>C:\Program Files\GO (3.1.2338-6)\bin\GrandOrgue.exe
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mark>C:\Program_Files\GO_(3.1.2338-6)\bin\GrandOrgue.exe
The system cannot find the path specified.

**Comment by Bumblebee001** [comment]
Regarding the installation file.... you seem like you have not yet understood what I am trying to point out. What you are doing is confusing me at best and no where near what I am pointing at.

In Summary, sourceforge GO downloads were "installable files" after unzipping. The one available on GIThub is the compressed file of an already installed program as it would appear in C:\Program Files.

**Comment by oleg68** [comment]
> C:\Users\mark>C:\Program Files\GO (3.1.2338-6)\bin\GrandOrgue.exe
> 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

It is because the path contains spaces. The right command is (with quotes)

"c:\Program Files\GO (3.1.2338-6)\bin\GrandOrgue.exe"

> Regarding the installation file.... you seem like you have not yet understood what I am trying to point out. What you are doing is confusing me at best and no where near what I am pointing at.

I'm trying to localise a bug: GrandOrgue did not run after unzipping without any visible error message. I've tried, but I couldn't reproduce it in my environment, so I ask your to reproduce it and to provide me an information for un

> In Summary, sourceforge GO downloads were "installable files" after unzipping. The one available on GIThub is the compressed file of an already installed program as it would appear in C:\Program Files (GO folder, subfolders and files).

It is not necessary to unzip it to ``c:\Program Files``. You may extract the zip somewhere else. For example, to `C:\Users\mark`, and run it from there.

``C:\Users\mark\grandorgue-0.3.1.2338-6.os.windows.x86_64\bin\GrandOrgue.exe``

**Comment by Bumblebee001** [comment]
The program runs with the " ". It also runs if I create a shortcut to that exe file.
Both versions run (old and new). I have no problem with them.

Still a fact still remains: the file available on GIThub does not appear to be an installation file that runs the user to a sequence of where to install, whether to rename or anything like I'm used to seeing with previous versions available on source forge. All one needs to do is unzip and drag the folder to whatever place one chooses and renames manually the folder within a file manager. Whoever created the GIThub file simply zipped up his installation and posted it but did not create the "setup" programme. I wouldn't know anything about how such programmes are created but I'm sure Martin Koegler or another member of the team would be able to enlighten us further. It does not make a difference to me really as long as everything works but anyone who may be installing GO for the first time might very well run into issues with the default paths to where things are stored as the folders (eg C:\users\****\GrandOrgue\Audio recordings) would have to be created manually one by one (and there are 5 of them: Audio recordings, MIDI recordings, Organ packages, Organs, Settings) in the absence of a proper setup that runs and installs things automatically.

Mark

**Comment by oleg68** [comment]
Mark, 

This is a setup program for the latest release in github: https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2341-1.os/grandorgue-0.3.1.2341-1.os.windows.x86_64.exe

Oleg

**Comment by Bumblebee001** [comment]
YES! That's OK - perfect - almost (the shortcut was not created and had 
to do it manually).
I wonder what file I used in the other version.
Case closed.
