### ISSUE TITLE
Installation versions on different mac os

### ISSUE THREAD

**Issue by mattrixed** [oleg68/GrandOrgue#39]
I note that these versions will only install on Catalina and up won’t even install on one os back Mojave.  When you make the Mac version is there a way of ticking comparability for older os’s? A lot of people on older hardware only have access to high Sierra 10.13 or even older etc.

I realise this may not be possible due to hardware and software differences but if there was a way of making same latest versions but for high Sierra or El Capitan etc that would be great for compatibility.

as with sound forge, 20 different versions available for Mac but none say which OS they are for…!

**Comment by oleg68** [comment]
1. When GO is built on OSx version XX.Z then the result is runnable on OSX XX.Z and on all versions above.
2. I don't know another capability of building GO for OSx rather running this build on the same MacOs machine. For linux there is an alternative - to build in a docker container, but it is not for Mac
3. All the versions are built on GitHub Runner machines: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
4. The oldest OsX version available in GitHub Runners is 10.15
5. So It is not feasible to build version for elder OSx versions using the same technology stack
6. Any proposals of how to do this are welcome

**Comment by mattrixed** [comment]
Thanks Oleg - I suspected something like that.  I wonder how the previous compilers did it?

Ok will try and have a look!
