### ISSUE TITLE
[Feature request] Binary for macOS Apple Silicon

### ISSUE THREAD

**Issue by ghost** [oleg68/GrandOrgue#44]
It would be great if GrandOrgue could be also compiled for Apple Silicon.

**Comment by oleg68** [comment]
1. GitHub now does not provide workers with MacOs arm64, so I cann't compile it.
2. Apple Silicon has a capability with x86_64 applications. GO/osx/x86_64 should run at Apple Silicon. Could you test it?

**Comment by oleg68** [comment]
https://github.com/actions/runner/issues/805

**Comment by uctcs** [comment]
Oleg,

I found two issues:

1. There is a problem with the audio subsystem. GrandOrgue asks for weird sample per buffers settings, e.g. 14 or 15. If you set this value, the sound output is very disturbed.
2. Quittung GrandOrgue crashes the program.

**Comment by oleg68** [comment]
1. Are these issues on M1?
2. About Samples per Buffer
    1. What sound device are you using?
    2. What happens when you specify a large sample per buffer settings, ex. 64 or 128?
    3. Could you try to select Audio/Midi settings -> Audio Output -> Device -> Change and to try to change to another device? Do all devices require 14 or 15?
3. Please open a separate issue about the crash with the crash report attached. Having the staktrace it is always easy to fix the crash.

**Comment by oleg68** [comment]
If you have the access to Mac M1, could you try to compile GO by you own? What is the result?

**Comment by oleg68** [comment]
The same issue with Samples per Buffer has been reported at https://sourceforge.net/p/ourorgan/discussion/962125/thread/cd62bdea40/

**Comment by uctcs** [comment]
Oleg, sorry for the late reply. It took me a while to compile the program. The build script did not work for me. I finally managed to compile the program manually. An Apple Silicon program was compiled. However, GrandOrgue crashed directly. Attached is the crash report. Any ideas what I should try now?

[CrashReport.txt](https://github.com/oleg68/GrandOrgue/files/6872074/CrashReport.txt)

**Comment by oleg68** [comment]
The crash report looks like the code is not compiled properly: ``Code Signature Invalid`` in dyld3::MachOFile::compatibleSlice

Maybe https://discussions.apple.com/thread/252516643 will help you.

**Comment by uctcs** [comment]
Unfortunately the link did not help me. I am not a very experienced programmer.

I deleted the whole project and started from scratch. Attached you will see the whole screen output. Maybe you can see the problem.

[build.log](https://github.com/oleg68/GrandOrgue/files/6872281/build.log)

**Comment by oleg68** [comment]
@uctcs I noticed that all devices connected with the RtAudio GrandOrgue Port require sample per buffers settings 15 a created a separate issue: #54

**Comment by uctcs** [comment]
I still have the immediate crash when running the self-compiled version of GO on Apple Silicon. I always compile GO when you push new changes, but unfortunately this problem has not been fixed yet.

[CrashReport.log](https://github.com/oleg68/GrandOrgue/files/6949230/CrashReport.log)

**Comment by oleg68** [comment]
I cann't help you with self-compiled version, because I don't know a right way for compiling for M1. 

ould you try to run the precompiled intel version [0.3.1.2341-9](https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2341-9.os/grandorgue-0.3.1.2341-9.os.osx.x86_64.dmg)

Is the audio subsystem issue #54 solved there?

**Comment by oleg68** [comment]
I cannot build for M1 until Github enables support of it https://github.com/actions/virtual-environments/issues/2187
