### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by mattrixed** [oleg68/GrandOrgue#45]
Hello!  Gradually getting worse with every version the language in the program is defaulting to another language - it used to be mostly all in English but this last ver 6 is in polish?  all the menus and GO setting pages are in another language making it very difficult to navigate - is this something perhaps that should auto detect native language of OS?

For ref I'm on Mac OS X Catalina

**Comment by oleg68** [comment]
I've tested it. The reason is wxLocale::getSystemLanguage() returns `German`. I don't know why.

I'm going to add a capability of choosing another language in GrandOrgue Settings

**Comment by oleg68** [comment]
Already fixed in 0.3.1.2341-6.os

**Comment by oleg68** [comment]
https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-8.os

Added capability of selecting a language in a Settings menu.
