### ISSUE TITLE
Running headless

### ISSUE THREAD

**Issue by ajvdw** [oleg68/GrandOrgue#47]
I am looking to a proper solution to run GrandOrgue without a screen on a Raspberry PI 4. Loosing all the UI stuff would free up some resources as well. What's the best approach? I also want to send some commands to the core to store some settings before shutting down properly.

**Comment by oleg68** [comment]
1. You may connect a monitor, run GO, make settings, store them and close GO
2. Next time you may run GO without a screen.

But I doubt that GO can ever run without a screen.
