### ISSUE TITLE
aarch64 deb packages not installable in 64-bit ARM Debian - should't it be arm64?

### ISSUE THREAD

**Issue by lbssousa** [oleg68/GrandOrgue#63]
I tried to install grandorgue aarch64 deb packages in my Rasperry Pi OS 64-bit (beta), but if failed due to several dependencies conflicts. The problem is that it requires dependencies for arch `aarch64`, but in Debian/Ubuntu the correct arch is `arm64`.

Could you update your CI/CD to build deb packages for `arm64` architecture?

**Comment by oleg68** [comment]
@lbssousa could you test the intermediate build from https://github.com/oleg68/GrandOrgue/actions/runs/1130664878 ?

**Comment by lbssousa** [comment]
@oleg68 Yes, I've managed to install these packages correctly. Thank you!

**Comment by oleg68** [comment]
Fixed in https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-11.os
