### ISSUE TITLE
Program settings window opens on startup

### ISSUE THREAD

**Issue by paolo2504** [oleg68/GrandOrgue#66]
I saw somewhere here or maybe on sourceforge forum this issue. The settings window opens almost everytime the program is launched, apparently without any reason. I was not able to find any relation , for example with sw version update, sampleset update, cache update, settings change... It just opens and it is annoying even if, i do admit, not a fatal issue!

**Comment by oleg68** [comment]
The setting window is open in two cases
1. The sound card is configured but cann't be accwssed
2. There are no active midi input devices.

I agree that displaying a reason why the setting is open would be a good enhancement.

**Comment by paolo2504** [comment]
Acknowledge. In my case it means no input midi device. Uhm.. it happens I download and install new version of go and I launch it to see all is ok even if not connected to my organ…. It also happens sometime I want just review some organs to set general stops… well, don’t really see the need to open settings.  it would be easier to show some led blink to advise “no midi” or “no audio” device; then we open settings…
