### ISSUE TITLE
Main Window not completely visible

### ISSUE THREAD

**Issue by ajvdw** [oleg68/GrandOrgue#71]
The issue was mentioned on SourceForge and closed (GTK3 related).
On a Raspberry PI it still exist (64 bit Raspberry PI OS and also the 32 bit version), the icons and settings in the toolbar are only partly visisble (2 pixels or so).

I solved it by changing the following code (GrandOrgueFrame.cpp line 267 or so).

	SetMaxClientSize(wxSize(tb->GetBestSize().GetWidth() + 10, 0));
	SetSize(GetMaxSize());
	int nr = wxDisplay::GetFromWindow(this);
	wxDisplay display(nr != wxNOT_FOUND ? nr : 0);
	Move(display.GetClientArea().GetPosition().x + 1, display.GetClientArea().GetPosition().y + 1);

The cause is the last zero, in SetMaxClientSize. I changed it to 

SetMaxClientSize(wxSize(tb->GetBestSize().GetWidth() + 10,tb->GetBestSize().GetHeight() + 10));
	
The + 10 is probably not necessary.

**Comment by oleg68** [comment]
@ajvdw 

I had a similar issue with an intermediate github release (https://github.com/oleg68/GrandOrgue/actions/runs/1108712609). At the same time the menus and the file open dialogs had unusual look-and-feel.

But this issue just dissappeared after rebuilding from the source and no more reproduced.

1. Which version of GO do you use?
2. Could you post here the screenshot (is it the same as was mine)?
3. Could you post a URL to the SourceForge issue?
4. If you propose some change in the source code, you may creare a Pull Request in the github

**Comment by oleg68** [comment]
I found https://sourceforge.net/p/ourorgan/bugs/53/

**Comment by ajvdw** [comment]
I found out, that the raspberry build script for GO hosted on https://github.com/djbottrill/GrandOrguePi gets the source code from https://github.com/e9925248/grandorgue.git. The last commit was from  Jun 21, 2020. I will try to change the build script so it uses this repository. Is it an idea to include the Raspberry PI build script your repository?

**Comment by oleg68** [comment]
@ajvdw  This repo has already builds for debian-arm-based linux, including Respberry PI. Please try to use the [last release](https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-12.os)

**Comment by ajvdw** [comment]
Which build shell script should I use for building? The ones I tried complain about  ImageMagick_convert_EXECUTABLE-NOTFOUND just after it build an imageconverter... But it tries to use ImageMagick if I do 

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y cmake g++ pkg-config rpm file \
  libjack-dev libfftw3-dev zlib1g-dev libasound2-dev libwavpack-dev libudev-dev \
  libwxgtk3.0-gtk3-dev docbook-xsl xsltproc gettext po4a imagemagick

imagemagick is cannot be found. Shouldn't the makefile use the imageconverter it just built?

**Comment by oleg68** [comment]
I managed to reproduce this issue: I built GO in debian 9 with libwxgtk3.0-dev instead of libwxgtk3.0-gtk3-dev. In this case GO runs on modern OS (I tested on fedora 34) with metacity look-and-feel and the main window is not fully visible.

There is another related to the size of the main window: #72 

Another problem is that not all tools are visible if there are more than two output audio channels.

I'm going to work on them.

**Comment by oleg68** [comment]
@ajvdw 

> Which build shell script should I use for building? 

What OS are you using for building? There are build scripts only for debian/ubuntu, fedora and opensuse. Other distributions lack necessary packages.

You can install binaries already built for Raspberry 64-bit: https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2341-12.os/grandorgue_0.3.1.2341-12.os_arm64.deb https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2341-12.os/grandorgue-demo_0.3.1.2341-12.os_all.deb https://github.com/oleg68/GrandOrgue/releases/download/0.3.1.2341-12.os/grandorgue-resources_0.3.1.2341-12.os_all.deb

If you want to make changes and compile them you can fork this repository, and push your changes to it. Then Github automatically will build GO for all systems, including Raspberry PI, and you can get the new binaries from the `Actions` button.

**Comment by ajvdw** [comment]
using the release above, starts the mainwindow visible but the controls on the righthand side of the toolbar are not visible (they are shown in a dropdown as text). The log says:

` (GrandOrgue:1073): Gtk-WARNING **: 11:39:55.318: Negative content width -5 (allocation 2, extents 4x3) while allocating gadget (node toolbar, owner GtkToolbar)
`
i assume this is related to the problem.

**Comment by oleg68** [comment]
>  the righthand side of the toolbar are not visible (they are shown in a dropdown as text)

I is the same as #72 on Mac Os

**Comment by ajvdw** [comment]
Oleg,

More or less.
It lists the captions / shortcuts of the controls (2). Panic and another one.
But it goes away by removing the GrandOrgueConfig file.
I opens property if the config does not exist.
The next time when it exists it’s back.
So I think it has to do with an overflow in the config.

AJ

**Comment by oleg68** [comment]
@ajvdw The new release 0.3.1.2341-13.os should fix it.

But the size of the main window is stored in the Organ Setting file. So it may be small after opening an organ. In this case resize the window manually and `File`->`Save` the new size
