### ISSUE TITLE
Weird "menu" in main bar ..

### ISSUE THREAD

**Issue by Jean-Gabriel1982** [oleg68/GrandOrgue#72]
On latest release (previous one too), I noticed that we have on main bar, little "commas" at the right.
When we click on it, a kind of menu appears, weird... please see the capture..

![Capture d’écran 2021-08-19 à 09 14 25](https://user-images.githubusercontent.com/20370038/130025027-c2e45cec-50aa-4ae3-84cc-b69bd24e1a8f.png)

**Comment by oleg68** [comment]
The reason is wxToolBar::GetBestSize returns the same as wxToolBar::GetMinSize on Mac Os.

I need to find another way for determining the optimal size of the toolbar.

**Comment by oleg68** [comment]
I can not fix it because it is a bug in wxWidgets. But the next release proposes a workaround: to resize this window manually and to save the new size with `Save` menu
