### ISSUE TITLE
80 Add ASIO support to github builds

### ISSUE THREAD

**Issue by oleg68** [oleg68/GrandOrgue#8]
Now ASIO is disabled. It'd be nice to enable it in github builds

**Comment by mattrixed** [comment]
Yes! Please enable asio support for windows builds.  I am mainly linux/mac but i have need for asio to properly use multichannel output with windows and a touchscreen setup.

**Comment by oleg68** [comment]
@mattrixed You can try the intermediate build https://github.com/oleg68/GrandOrgue/actions/runs/893986050 for trsting ASIO. Now only PortAudio supports ASIO. I'm working on support in RtAudio.

**Comment by oleg68** [comment]
https://github.com/oleg68/GrandOrgue/releases/tag/0.3.1.2341-3.os
