### ISSUE TITLE
Mac Language Translations Do Not Set to System Default on First Launch

### ISSUE THREAD

**Issue by pgcrowe** [oleg68/GrandOrgue#84]

**Comment by oleg68** [comment]
Coud you post a screenshot of the Settings->Options page on First Launch here?

**Comment by pgcrowe** [comment]
Sure. This screenshot shows that German is the default language. If English is selected (and GrandOrgue is restarted), (Default) remains next to German in the drop down menu.
<img width="721" alt="Screen Shot 2021-09-01 at 11 56 33 AM" src="https://user-images.githubusercontent.com/54217096/131704349-ca27e908-e5da-45ec-9452-87e625e8bcdb.png">

**Comment by pgcrowe** [comment]
This screenshot shows that after English is selected and GrandOrgue is restarted, German is still the "default" language. <img width="722" alt="Screen Shot 2021-09-01 at 12 00 56 PM" src="https://user-images.githubusercontent.com/54217096/131704816-c88fae72-f6a7-4ca9-aaf3-af46d5b111b8.png">

**Comment by oleg68** [comment]
wxLocale::getSystemLanguage() incorrectly returns `German`.

I can not fix it because it is a bug of wxWidget, not of GrandOrgue. I added capability of changing settings manually specially as a workaround of this bug.

See https://github.com/oleg68/GrandOrgue/issues/45 for more details.
