### ISSUE TITLE
Mac build fails

### ISSUE THREAD

**Issue by uctcs** [oleg68/GrandOrgue#9]
Hello Oleg,

I tried to build GrandOrgue for macOS. Building the master branch fails. I attach the complete log files.

I also tried to build the branch "feature/github-build". This runs through but the resulting application crashes without an error message.

Peter

[Mac_build.zip](https://github.com/oleg68/GrandOrgue/files/6287998/Mac_build.zip)

**Comment by oleg68** [comment]
Building for macOs was fixed in 3ce93b70898f0d9dfa8c0642237755a88e792dbf
Yesterday I merged feature/github-build to master. Please try building against master or use files built on github
https://github.com/oleg68/GrandOrgue/actions/runs/734226265
